Testnet theme
symbol/symbol-explorer pull request #971
Opened 2021-11-18 14:50 UTC by AnthonyLaw

- Add Testnet dark mode theme

![image](https://user-images.githubusercontent.com/5649156/142438140-51ecb042-4326-4633-a461-ffd47c050626.png)

2021-11-18 15:22 UTC, rg911 requested changes

2021-11-18 15:49 UTC, AnthonyLaw commented on src/components/ThemeToggle.vue
> +		if (theme === null)
yeah, It was removed from `lint --fix`, but I will change that when work on this Issue  https://github.com/symbol/symbol-explorer/issues/694

2021-11-19 15:45 UTC, OlegMakarenko approved these changes
Later, we should use the latest Design System and replace the custom variables with design tokens.

2021-11-19 17:30 UTC, AnthonyLaw commented
> Later, we should use the latest Design System and replace the custom variables with design tokens.

Yes, that is the plan 👍🏼

2021-11-19 17:37 UTC, rg911 approved these changes

2021-11-19 18:02 UTC, merged